#minimum_pre_commit_version: 1.15.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: trailing-whitespace # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-ast # Simply check whether files parse as valid python.

  # ----- Local Hooks ----------------------------------------------------------------------------------------------->
  # - repo: local
  #   hooks:
  #     - id: sort-pylint-spelling-words
  #       name: Sort PyLint Spelling Words File
  #       entry: python .pre-commit-hooks/sort-pylint-spelling-words.py
  #       language: system
  #       files: ^\.pylint-spelling-words$

  #     - id: check-changelog-entries
  #       name: Check Changelog Entries
  #       entry: python .pre-commit-hooks/check-changelog-entries.py
  #       language: system
  # <---- Local Hooks ------------------------------------------------------------------------------------------------

  # ----- Formatting ------------------------------------------------------------------------------------------------>
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.5+
        args: [--py3-plus]
        exclude: (^src/saltfactories/utils/saltext/.*\.py)

  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        args: [-l 100]
        exclude: src/saltfactories/version.py

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^(.*\.rst|docs/.*\.rst|src/saltfactories/.*\.py)$
        additional_dependencies:
          - black==22.3.0
  # <---- Formatting -------------------------------------------------------------------------------------------------

  # ----- Security -------------------------------------------------------------------------------------------------->
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against Salt
        args: [--silent, -lll, --skip, B701]
        exclude: >
          (?x)^(
              tests/.*
          )$
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, B701]
        files: ^tests/.*
  # <---- Security ---------------------------------------------------------------------------------------------------

  # ----- Code Analysis --------------------------------------------------------------------------------------------->
  #  - repo: https://github.com/pycqa/flake8
  #    rev: '4.0.1'
  #    hooks:
  #      - id: flake8
  #        exclude: ^(src/saltfactories/version\.py|\.pre-commit-hooks/.*\.py)$
  #        additional_dependencies:
  #        - flake8-mypy-fork
  #        - flake8-docstrings
  #        - flake8-typing-imports
  #        - pydocstyle>=6.1.1
  # <---- Code Analysis --------------------------------------------------------------------------------------------->

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest tests
        language: system
        pass_filenames: false
        always_run: true
